### ISSUE TITLE
[TypeError: Cannot call method 'run' of undefined]

### ISSUE THREAD

**Issue by ans-4175** [timseverien/throttled-promise#1]
Well, i put some ThrottlePromises in array then called ThrottlePromise.all(array,3), with just 3 threads. But it produce that error and failed all.
How could that happen ?

**Comment by ans-4175** [comment]
I fix this by edit the index.js in `function next` with this:

```
if (typeof tp !== 'undefined') {
        var p = tp.run();

        p.then(function(value) {
          values[tp.index] = value;

          // Not everything is completed, so move on to next
          if (++completed < count) next(next, resolve, reject);

          // Everytimg seems completed, Promise will handle the rest
          else resolve(values);
        }).catch(reject);
      }
```

**Comment by timseverien** [comment]
Can you reproduce this and show an example? At line 27, all array items are checked whether they are ThrottledPromises. If not, it should throw the error `ThrottledPromise.all() only accepts a list of ThrottledPromises.`.
