### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by altintx** [timseverien/throttled-promise#3]
I've run into something similar to #1.

    ThrottledPromise.all(arrayOfEightTPs, 3); // network heavy

Gets through [0]-[5] just fine, but then my debugger will pause inside throttled-promise/index.js on

    if(!(tp instanceof ThrottledPromise) && tp.value) {

With ```TypeError: Cannot read property 'value' of undefined```.

tp is definitely undefined at runtime in that error state.

As far as I can tell, ```tryFinish``` isn't considering whether other promises have already started; only that there are incomplete promises. This leads to ```next()``` being run more times than there are promises passed to ```.all()```

In my case, I added 

    if (promises.length == 0) return;

to the top of ```next()``` and rely on one of the other ongoing promise's resolution to resolve ```.all()```.

Using throttled-promise 0.2.0 and Node 7.1.0.

**Comment by timseverien** [comment]
I’ve basically rewrote the whole library and tagged it 1.0.0. Also, I have made the tests slightly more robust, and everything seems to work nicely now. Could you please verify this for me?

**Comment by altintx** [comment]
Ran without error in that department. Worth noting that I had to change the require line

```
var ThrottledPromise = require("throttled-promise")
```

vs

```
var ThrottledPromise = require("throttled-promise").default
```

Thanks!

**Comment by timseverien** [comment]
Ah, I’m an idiot. I’ll fix it immediately. Thanks for verifying it works now!
